#!/bin/sh
# shellcheck disable=SC1072,SC1073

# DEPENDENCIES
# - $EDITOR envvar / a text editor (fallback: vi)
# - shellcheck
# - chmod

# Text editor (fallback: vi)
EDITOR=${EDITOR:-vi}
# Your scripts directory (fallback: ~/.local/bin)
SCRIPTS=${SCRIPTS:-$HOME/.local/bin}

prog="$0"

err() {
	# Usage: err [error message]
	# Prints [error message] and exits as error
	printf 'ERROR %s\n' "$1"
	exit 1
}

usage() {
	# Usage: usage
	# Prints help info and exits successfully
	printf 'Usage: %s <scriptname>\n\n' "$prog"
	printf 'scriptname: filenames in %s\n' "$SCRIPTS"
	exit 0
}

prompt_create() {
	# Usage: prompt_create <script filename>
	# Prompt user to create script if it doesn't exist in $SCRIPTS
	printf 'Script %s does not exist. Create it? (y/n) ' "$1"
	read -r ans

	case $ans in
		# ':>' creates a file
		y|yes) 
			:> "$SCRIPTS/$1" || err "Failed to create $SCRIPTS/$1" 
			printf '#!/bin/sh' >> "$SCRIPTS/$1"
		;;
		# exit if it ain't y | yes
		*) exit 0 ;;
	esac
}

# print usage stuff when no arg provided
[ -z "$1" ] && usage

# check if file/dir does not exist
[ ! -f "$SCRIPTS/$1" ] && [ ! -d "$SCRIPTS/$1" ] && prompt_create "$1"

# open script in editor
$EDITOR "$SCRIPTS/$1" || err "Failed to run $EDITOR \"$SCRIPTS/$1\""

# make sure its executable
chmod 755 "$SCRIPTS/$1" || err "Failed to make \"$SCRIPTS/$1\" executable"

# always shellcheck your scripts to be a better shell scripter
shellcheck "$SCRIPTS/$1" || err "Failed to shellcheck \"$SCRIPTS/$1\""
