#!/bin/sh

[ -z "${1}" ] && printf 'Usage: %s <file>\n' "${0}" && exit 1
file=${1}
[ ! -f "${file}" ] && printf 'Invalid file\n' && exit 1

case "${file}" in
	*.tar.bz2) tar xjf "${file}" ;;
	*.tar.gz) tar xzf "${file}" ;;
	*.bz2) bunzip2 "${file}" ;;
	*.rar) unrar x "${file}" ;;
	*.gz) gunzip  "${file}" ;;
	*.tar) tar xf  "${file}" ;;
	*.tbz2) tar xjf "${file}" ;;
	*.tgz) tar xzf "${file}" ;;
	*.zip) unzip "${file}" ;;
	*.Z) uncompress "${file}" ;;
	*.7z) 7z x "${file}" ;;
	*.xz) unxz "${file}" ;;
	*)
		printf 'Unknown file %s\n' "${1}"
		exit 1
		;;
esac
