#!/bin/sh

XDG_DOCUMENTS_DIR=${XDG_DOCUMENTS_DIR:-"${HOME}/Documents"}

NOTE_DIR=${NOTE_DIR:-"${XDG_DOCUMENTS_DIR}/note"}

prog=${0}

entriesdir="${NOTE_DIR#/}/entries"
importantdir="${NOTE_DIR#/}/important"

main() {
	# Program's entry point

	ensure_directories

	[ -z "${1}" ] && usage

	case "${1}" in
		-h) usage ;;
		new) command_new "${2}" "${3}" ;;
		ls) command_ls "${2}" ;;
		*) err "Invalid command. See \"${prog} -h\"" ;;
	esac
}

ensure_directories() {
	# Usage: ensure_directories
	# Ensure necessary directories exist

	[ ! -d "${entriesdir}" ] && mkdir -p "${entriesdir}"
	[ ! -d "${importantdir}" ] && mkdir -p "${importantdir}"
}

command_new() {
	# Usage: command_new [title | <title> -i]
	# Create a new note.

	title="${1:-<TITLE>}"
	[ -z "${title}" ] && err "command_new() title argument missing"

	dt="$(date -u +'%Y-%m-%d-%H-%M-%S')"

	fpath="${entriesdir}/${dt}.md"

	:> "${fpath}"

	{
		printf '# %s\n\n' "${title}"
		printf '    #TAGS:'
	} >> "${fpath}"

	${EDITOR} "${fpath}"
}

command_ls() {
	# Usage: command_ls [title]
	# List all note entries in entry ls format

	if [ -n "${1}" ]; then
		list_notes | grep -i "${1}"
	else
		list_notes
	fi
}

list_notes() {
	# Usage: list_notes
	# List out all notes in get_entry_ls_format

	for i in "${entriesdir}"/*; do
		get_entry_ls_format "${i}"
	done
}

sanitize_title_for_fname() {
	# Usage: sanitize_title_for_fname [title]
	# Sanitizes note titles to be file/directory names

	printf '%s\n' "${title}" | \
		sed 's/[\\\/\:\*\?"<>|\ ]/_/g'
}

get_entry_ls_format() {
	# Usage: get_entry_ls_format <note file path>
	# Print out the note's title and file name in the format of
	#   [BASENAME] TITLE
	# where BASENAME does not have a file extension
	fpath="${1}"

	[ -z "${fpath}" ] && \
		err "get_entry_ls_format() missing fpath argument"

	fname="$(basename "${fpath}")"
	title="$(get_title "${fpath}")"

	printf '[%s] %s\n' "${fname%.md}" "${title}"
}

get_title() {
	# Usage get_title <file path>
	# Get note title
	fpath="${1}"

	[ -z "${fpath}" ] && err "get_title() missing fpath argument"

	title="$(sed 1q "${fpath}")"
	printf '%s\n' "${title#\# }"
}

usage() {
	# Usage: usage
	# Print help info

	while IFS= read -r line; do
		printf '%s\n' "${line}"
	done <<-EOF
USAGE
  ${prog} new [title | <title> -i]

COMMANDS
  new [title | <title> -i]:
    Create a new note. Optionally specify a title to quickly add one to
    the note (can be changed while editing). Specifying a title with the
    -i flag will mark the note as important.
	EOF

	exit 1
}

err() {
	# Usage: err <error message>
	# Throw an exception with a message

	printf '%s error: %s\n' "${prog}" "${1}"
	exit 1
}

main "$@"
