#!/bin/sh

# rsuf - remove suffix
# 
# strip out some characters at the end of each line
# It is designed to be used with vi/m and its clones, for uncommenting
# lines of code. Used in conjuction with rpre (remove prefix)
#
# Script originally "ucmt" written by rwxrob (https://rwxrob.tv)
# https://github.com/rwxrob/dot/blob/main/scripts/ucmt
# changes:
# - replaced shebang with bin sh
# - now deletes things at the end of the line
#
# DEPENDENCIES
# - read
# - echo

while IFS= read -r line; do 
	# Basically take the line, start looking at last col and strip out text
	# in argument 1
	# i.e 
	# $ echo '/* Hello world */' | rsuf ' */'
	# /* Hello world
	echo "${line%${1}}"
done
