#!/bin/sh
# shellcheck disable=SC2124

query=$@

case $query in 
	gopher://*) lynx "${query}" ;;
	gemini://*) amfora "${query}" ;; 
	http://*|https://*) w3m "${query}" ;; 
	*) w3m "https://lite.duckduckgo.com/?q=${query}";; 
esac
