#!/bin/sh
# shellcheck disable=SC2124

query=$@

case $query in 
	gopher://*) lynx "${query}" ;;
	gemini://*) amfora "${query}" ;; 
	http://*|https://*) HOME="${XDG_DATA_HOME}/w3m" w3m "${query}" ;; 
	*) HOME="${XDG_DATA_HOME}/w3m" w3m "https://duckduckgo.com/?q=${query}";; 
esac
